-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 17:54:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema turismoso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema turismoso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `turismoso` DEFAULT CHARACTER SET latin1 ;
USE `turismoso` ;

-- -----------------------------------------------------
-- Table `turismoso`.`guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismoso`.`guia` (
  `idguia` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `valor_hora` DOUBLE NOT NULL,
  PRIMARY KEY (`idguia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `turismoso`.`lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismoso`.`lugar` (
  `idlugar` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `guia_idguia` INT NOT NULL,
  PRIMARY KEY (`idlugar`, `guia_idguia`),
  INDEX `fk_lugar_guia_idx` (`guia_idguia` ASC),
  CONSTRAINT `fk_lugar_guia`
    FOREIGN KEY (`guia_idguia`)
    REFERENCES `turismoso`.`guia` (`idguia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `turismoso`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismoso`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `lugar_idlugar` INT NOT NULL,
  `lugar_guia_idguia` INT NOT NULL,
  PRIMARY KEY (`idcliente`, `lugar_idlugar`, `lugar_guia_idguia`),
  INDEX `fk_cliente_lugar1_idx` (`lugar_idlugar` ASC, `lugar_guia_idguia` ASC),
  CONSTRAINT `fk_cliente_lugar1`
    FOREIGN KEY (`lugar_idlugar` , `lugar_guia_idguia`)
    REFERENCES `turismoso`.`lugar` (`idlugar` , `guia_idguia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
